config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/lists')

  resources :users, only: [:create]

  get '/signup', to: 'users#new'
  delete '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'

  resources :lists do
    resources :items, only: %i[update create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  enum status: [:not_started, :in_progress, :completed]

  belongs_to :list
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :user

  def percent_complete
    return 0 if total_items.zero?

    (100 * completed_items.to_f / total_items).round
  end

  def completed_items
    @completed_items ||= items.completed.count
  end

  def total_items
    @todo_items ||= items.count
  end

  def status
    case percent_complete.to_i
    when 0
      'Not started'
    when 100
      'Complete'
    else
      'In progress'
    end
  end

  def badge_color
    case percent_complete.to_i
    when 0
      'dark'
    when 100
      'success'
    else
      'info'
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  # rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def authenticate_user!
    redirect_to login_path unless current_user
  end

  def current_user
    @current_user ||= begin
      return nil unless session[:user_id]

      User.find(session[:user_id])
    end
  end

  def logged_in?
    session[:user_id] == nil
  end

  def redirect_to_lists
    redirect_to lists_path
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list
  before_action :set_item, only: %i[update destroy]

  def index
    @items = @list.items
  end

  def new
    @item = @list.items.build
  end

  def create
    @item = @list.items.build(item_params)

    if @item.save
      redirect_to @item.list, notice: 'Todo item was successfully created'
    else
      redirect_to @item.list, notice: 'Error while creating item!!!'
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @item.list
    else
      redirect_to @item.list, notice: 'Error while saving!!!'
    end
  end

  def destroy
    @item.destroy

    redirect_to list_path(@list)
  end

  private

  def set_list
    @list = current_user&.lists&.find(params[:list_id])
  end

  def set_item
    @item = @list.items.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:description, :status, :completed_at, :list_id)
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: %i[show edit update destroy]
  def index
    @lists = current_user.lists
    @item = Item.new
    @list = List.new
  end

  def show
    @item = Item.new
  end

  def new
    @list = List.new
  end

  def edit; end

  def create
    list = List.new(list_params)
    if list.save
      redirect_to lists_path, notice: "Todo list was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @list.update(list_params)
      redirect_to @list, notice: "Todo list was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: "Todo list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_list
    @list = current_user&.lists&.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:title).merge(user_id: session[:user_id])
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :redirect_to_lists, unless: :logged_in?, only: %i[new create]

  def new; end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = "Successfully logged in!"
      redirect_to lists_path
    else
      flash[:error] = 'Invalid login or password!'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You are logged out!"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    redirect_to lists_path unless logged_in?

    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Successfully registration!!!"
      redirect_to login_path
    else
      flash[:error] = 'Some info is invalid'
      redirect_to signup_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_type(type)
    case type
    when 'error'
      'danger'
    when 'success'
      'success'
    else
      'primary'
    end
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
  def item_statuses
    [['Not started', 'not_started'], ['In progress', 'in_progress'], %w[Completed completed]]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-light">
    <%= render 'shared/header' %>
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">
          <%= render 'shared/notice' %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="card-body">
  <div class="input-group mb-4">
    <%= form_with(model: list) do |f| %>
      <div class="input-group">
        <%= link_to 'Back', @list, class: 'btn btn-danger input-group-btn' %>
        <%= f.text_field :title, class: "form-control", placeholder: 'List name' %>
        <%= f.submit "Save", class: "btn btn-primary input-group-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/_list.html.erb
<div>
  <div class="card-header">
    <div class="row">
      <div class='col-1'>
        <%= button_to '', lists_path, class: 'btn-close m-1', method: :get %>
      </div>
      <div class="col-11">
        <%= turbo_frame_tag dom_id(list), class: 'd-flex justify-content-between' do %>
          <h5 class='m-1'>
            <b><%= list.title %></b>
            <span class="badge text-bg-<%= list.badge_color %>"><%= list.status %></span>
          </h5>
          <p class='text-secondary m-1'>
            <small><%= list.percent_complete %>% Complete (<%= list.completed_items %>/<%= list.total_items %>Todo items)</small>
          </p>
          <div>
              <%= link_to 'Edit', edit_list_path(list), class: 'btn btn-secondary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-body">
    <div class="progress mb-4">
      <div class="progress-bar bg-info" role="progressbar" style="width: <%= list.percent_complete %>%" aria-valuenow="<%= list.completed_items %>" aria-valuemin="0" aria-valuemax="100"></div>
    </div>

    <%= form_for([list, @item]) do |f| %>
      <div class="input-group mb-4">
        <%= f.text_field :description, class: "form-control", placeholder: 'Add to do item' %>
        <div class="input-group-append">
          <%= f.submit "Add", class: "btn btn-primary input-group-btn" %>
        </div>
      </div>
    <% end %>

    <ul class="list-group">
      <% list.items.each do |item| %>
        <% if item.completed? %>
          <li class='list-group-item bg-light'>
            <div class="d-flex justify-content-between">
            <span class="text-muted">
              <em><%= item.description %></em>
            </span>
              <div class="form-group">
                <div class="input-group gap-3">
                  <%= form_for [list, item] do |f| %>
                    <%= f.select :status, options_for_select(item_statuses, item.status), {}, class: 'form-select form-select-sm', :onchange => "this.form.submit();" %>
                  <% end %>
                  <%= link_to list_item_path(item.list, item.id), class: 'btn btn-danger btn-sm', data: {turbo_method: :delete}, remote: true do  %>
                    <i class="bi bi-trash"></i>
                  <% end %>
                </div>
              </div>
            </div>
          </li>
        <% else %>
          <li class='list-group-item'>
            <div class="d-flex justify-content-between">
            <span>
              <%= item.description %>
            </span>
              <div class="form-group">
                <div class="input-group gap-3">
                  <%= form_for [list, item] do |f| %>
                    <%= f.select :status, options_for_select(item_statuses, item.status), {}, class: 'form-select form-select-sm', :onchange => "this.form.submit();" %>
                  <% end %>
                  <%= link_to list_item_path(item.list, item.id), class: 'btn btn-danger btn-sm', data: {turbo_method: :delete}, remote: true do  %>
                    <i class="bi bi-trash"></i>
                  <% end %>
                </div>
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/lists/edit.html.erb
<div class="card">
  <div class="card-header">
    <h1>Editing Todo List</h1>

    <%= turbo_frame_tag dom_id(@list) do %>
      <%= render 'form', list: @list %>
    <% end %>
  </div>
</div>

app/views/lists/index.html.erb
<div class="card mt-5">
  <%= content_tag 'div', class: 'card-header d-flex justify-content-between' do %>
    <h5 class='m-0 text-dark'>
      Todo Lists
    </h5>
    <%= link_to 'New Todo List', new_list_path, class: 'btn btn-primary btn-sm' %>
  <% end %>

    <div class="card-body">
      <ul class="list-group">
        <% @lists.each do |list| %>
          <div data-controller="reveal" data-reveal-hidden-class="d-none">
            <li class="list-group-item d-flex justify-content-between">
              <%= link_to list, class: 'text-decoration-none' do %>
                <h6 class='m-0 text-dark'>
                  <b><%= list.title %></b>
                  <span class="badge badge-<%= list.badge_color %>"><%= list.status %></span>
                </h6>
                <p class='text-secondary m-0'>
                  <small><%= list.percent_complete %>% Complete (<%= list.completed_items %>/<%= list.total_items %> Todo items)</small>
                </p>
              <% end %>
              <div class="form-group">
                <button data-action="click->reveal#toggle" type="button" class="btn"><i class="bi bi-chevron-down"></i></button>
                <%= link_to list_path(list), class: 'btn btn-danger btn-sm', data: {turbo_method: :delete}, remote: true do  %>
                  <i class="bi bi-trash"></i>
                <% end %>
              </div>
            </li>
            <div data-reveal-target="item" class="d-none mt-4">
              <%= render 'lists/list', list: list, item: @item %>
            </div>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="card mt-5">
  <div class="card">
    <div class="card-header">
      <h3>New Todo List</h3>
    </div>
    <%= render 'form', list: @list %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="card mt-5">
  <%= render 'lists/list', list: @list, item: @item %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar bg-body-tertiary ">
  <div class="container-fluid">
    <%= link_to 'ToDo App', lists_path, class: 'navbar-brand' %>
    <div class="d-flex">
      <% unless logged_in? %>
        <%= link_to 'Log out', logout_path, class: 'btn btn-success', data: {turbo_method: :delete}, remote: true %>
      <% else %>
        <% if current_page?(login_path) %>
          <%= link_to 'Sign in', signup_path, class: 'btn btn-success' %>
        <% else %>
          <%= link_to 'Log in', login_path, class: 'btn btn-success' %>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_notice.html.erb
<% flash.each do |type, msg| %>
  <div
    data-controller="notification"
    data-notification-delay-value="2000"
    class="transition transform duration-1000 hidden"
    data-transition-enter-from="opacity-0 translate-x-6"
    data-transition-enter-to="opacity-100 translate-x-0"
    data-transition-leave-from="opacity-100 translate-x-0"
    data-transition-leave-to="opacity-0 translate-x-6"
  >
    <div class="alert alert-<%= notice_type(type) %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" data-action="notification#hide"></button>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="row d-flex justify-content-center align-items-center h-100">
  <div class="col-12 col-md-8 col-lg-6 col-xl-5">
    <div class="card bg-dark text-white" style="border-radius: 1rem;">
      <div class="card-body">
        <div class="mb-md-5 mt-md-4 pb-5">
          <h2 class="bold mb-2 text-uppercase">Sign in</h2>

          <%= form_for @user do |f| %>
            <div class="form-outline form-white mb-4">
              <%= f.text_field :username, placeholder: "Username", class: 'form-control form-control' %>
            </div>
            <div class="form-outline form-white mb-4">
              <%= f.text_field :email, placeholder: 'Email', class: 'form-control form-control' %>
            </div>
            <div class="form-outline form-white mb-4">
              <%= f.password_field :password, placeholder: "Password", class: 'form-control form-control' %>
            </div>
            <div class="form-outline form-white mb-4">
              <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: 'form-control form-control' %>
            </div>
            <%= f.submit "Create Account", class: 'btn btn-outline-light btn px-5' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>